src/pages/Login.jsx, src/style/_Login.scss
로그인 페이지 레이아웃이 망가지는 문제를 발견해 수정함.
=> fix: 로그인 페이지 오류 수정

src/App.js, src/components/RegisterForm/RegisterForm.jsx, src/components/RegisterForm/RegisterForm.scss, src/components/UserWelcome/UserWelcome.jsx, src/constants/URL.js, src/pages/Login.jsx, src/pages/MyPage.jsx, src/redux/actions/authActions.js, src/redux/actions/userActions.js, src/redux/reducers/AppState.js, src/redux/reducers/UserData.js, src/redux/reducers/index.js
=> [찬민] - 폼 검증 로직 추가

data.json, src/components/GroupList/GroupList.scss, src/pages/Group.jsx, src/pages/User.jsx, src/style/_Group.scss
- 페이지네이션 및 그룹 리스트 스타일 작업 결과물입니다.
@suhwan-cheon @SongGol @kimtaehyun98 @jane-k 
혹시 15인치 미만 모니터에서는 어떻게 보이는지 피드백 주시면 감사드리겠습니다!
=> feat: 그룹 리스트 페이지 UI 작업

src/pages/Login.jsx, src/pages/User.jsx, src/style/_Login.scss, src/style/_User.scss
푼 문제 목록이 다음과 같이 표시됩니다.
디자인 피드백은 언제나 감사드립니다.
=> feat: 푼 문제 리스트 출력 구현

src/pages/User.jsx
- 회원이 아닌 유저를 검색할 경우 나타나는 페이지입니다.
=> feat: 유저 404 페이지 제작

src/components/CreateGroupModal/CreateGroupModal.jsx, src/components/GroupGoal/GroupGoal.jsx, src/components/GroupGoal/GroupGoal.scss, src/components/GroupList/GroupList.jsx, src/components/ProblemsList/ProblemsList.jsx, src/components/ProblemsList/ProblemsList.scss, src/components/SolvedMemberList/SolvedMemberList.jsx, src/components/SolvedMemberList/SolvedMemberList.scss, src/constants/URL.js, src/pages/Group.jsx, src/pages/GroupDetail.jsx, src/pages/Rank.jsx, src/style/_Group.scss
=> [4월 3주차] - 그룹 백엔드 연동 작업

src/pages/Login.jsx
=> 로그인 실패 시 예외 처리

src/components/CreateGroupModal/CreateGroupModal.jsx, src/style/_Group.scss
1. 그룹 리스트와 광고 리스트의 높이를 통일함.
2. 그룹 리스트 상태 업데이트 후 새로고침을 수행하도록 함.
=> 그룹 리스트 코드 수정

src/components/GroupSearch/GroupSearch.scss, src/pages/User.jsx
=> fix: 차트 불러오는 동안 대체 텍스트 추가

src/components/GroupInfoModal/GroupInfoModal.jsx, src/components/GroupInfoModal/GroupInfoModal.scss, src/components/GroupList/GroupList.scss, src/pages/User.jsx, src/style/_Group.scss
=> 그룹 가입 시 유저, 그룹 디비에 등록 완료

src/components/RegisterForm/RegisterForm.jsx, src/components/RegisterForm/RegisterForm.scss, src/components/RegisterSuccess/RegisterSuccess.jsx, src/components/RegisterSuccess/RegisterSuccess.scss, src/components/Terms/Term.jsx, src/pages/Login.jsx, src/pages/Register.jsx
=> feat: 회원가입 성공 페이지 추가

src/components/GroupList/GroupList.jsx, src/components/GroupList/GroupList.scss, src/pages/User.jsx, src/style/_Group.scss, src/style/_User.scss
=> 그룹 리스트 레이아웃 수정

src/components/CreateGroupModal/CreateGroupModal.jsx, src/components/CreateGroupModal/CreateGroupModal.scss, src/pages/User.jsx, src/style/_User.scss
=> feat: 그룹 유형 기능 추가

src/components/GroupInfoMember/GroupInfoMember.jsx, src/components/GroupInfoMember/GroupInfoMember.scss, src/components/GroupInfoModal/GroupInfoModal.jsx, src/style/app.scss
=> 그룹원 목록 스타일 추가

src/App.js, src/components/GroupGoal/GroupGoal.jsx, src/components/GroupGoal/GroupGoal.scss, src/components/GroupMenu/GroupMenu.jsx, src/components/GroupNotification/GroupNotification.jsx, src/components/GroupNotification/GroupNotification.scss, src/components/GroupStatistics/GroupStatistics.jsx, src/components/ProblemItem/ProblemItem.jsx, src/components/ProblemItem/ProblemItem.scss, src/components/ProblemsList/ProblemsList.jsx, src/components/ProblemsList/ProblemsList.scss, src/hooks/getUserData.jsx, src/pages/GroupDetail.jsx, src/style/app.scss, src/styles.js
=> 그룹 상세페이지 ui작업

package-lock.json, package.json, src/App.js, src/components/Footer/Footer.scss, src/components/GuideMenu/GuideMenu.jsx, src/components/GuideMenu/GuideMenu.scss, src/components/Nav.jsx, src/components/RecommendedGroup/RecommendedGroup.jsx, src/components/RecommendedGroup/RecommendedGroup.scss, src/components/Tag/Tag.jsx, src/components/Tag/Tag.scss, src/pages/Guide.jsx, src/style/_Guide.scss, src/style/app.scss
=> [페이지 추가 : 학습 가이드 페이지]

src/components/GroupAttendance/GroupAttendance.jsx, src/components/GroupGoal/GroupGoal.jsx, src/components/GroupMenu/GroupMenu.jsx, src/components/GroupRank/GroupRank.jsx, src/components/ProblemSet/ProblemSet.jsx, src/components/ProblemSet/ProblemSet.scss, src/components/ProblemsList/ProblemsList.jsx, src/pages/GroupDetail.jsx
=> 출석부 기능 90% 구현

src/components/GroupAttendance/GroupAttendance.jsx, src/components/GroupAttendance/GroupAttendance.scss, src/components/GroupMenu/GroupMenu.jsx, src/components/GroupNotification/GroupNotification.jsx, src/components/GroupRank/GroupRank.jsx, src/components/ProblemSet/ProblemSet.jsx, src/components/ProblemSet/ProblemSet.scss, src/components/ProblemsList/ProblemsList.jsx, src/constants/URL.js, src/pages/GroupDetail.jsx, src/pages/User.jsx, src/style/_GroupDetail.scss
미완성 : 그룹 내 랭킹 페이지 / 대회, 채용정보 페이지
=> feat: 그룹 상세페이지 제작

src/components/GuideMenu/GuideMenu.jsx, src/pages/Group.jsx
"학습 가이드" - 유형 선택시 나오는 "그룹 생성하기" 버튼이 그룹 생성 모달과 연결이 안되어있어서 연결해주었습니다 😀
=> link createGroupModal in GuideMenu page

src/pages/Guide.jsx
기능은 추가하였으나, 되돌아올때 유형 안에 글자 ex) "파이썬, C++ 등 기초 프로그래밍 언어의 문법을 숙달하기 위한 과정입니다." 가 이쁘게 돌아오지 않음..
=> 학습 가이드 페이지 - 유형 두 번 클릭 시 되돌아오는 기능 추가

src/components/ContestNotice/ContestNotice.jsx, src/components/CreateGroupModal/CreateGroupModal.jsx, src/components/GroupMenu/GroupMenu.jsx, src/components/JobNotice/JobNotice.jsx, src/pages/Rank.jsx, src/style/_Rank.scss
=> feat: 전체 랭킹 페이지 초안

src/components/GroupRank/GroupRank.scss, src/pages/Rank.jsx, src/style/_Rank.scss
=> 랭킹 애니메이션 추가

src/pages/Rank.jsx
=> 그룹 인원 뒤에 '명' 텍스트 추가

src/components/GroupMenu/GroupMenu.jsx, src/components/ManageGroup/ManageGroup.jsx, src/pages/GroupDetail.jsx
=> feat(ManageGroup.jsx) : 그룹 관리 페이지 목업 추가

src/components/GroupSearch/GroupSearch.jsx, src/pages/Group.jsx, test.js
=> fix: 그룹 찾기 기능 수정
